# Generated by Django 3.2 on 2022-10-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('catalogoSunat', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=4, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('fechaFact', models.DateField(auto_now=True)),
                ('estaFacturado', models.BooleanField(blank=True, null=True)),
                ('iscanje', models.BooleanField(blank=True)),
                ('enlace', models.URLField(blank=True)),
                ('cadenaqr', models.CharField(blank=True, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogoSunat.tipodocumento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_factura', to='persona.persona')),
                ('ventaMovimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.movimiento')),
            ],
            options={
                'verbose_name': 'FaturaBoleta',
                'verbose_name_plural': 'FaturaBoletas',
            },
        ),
    ]
