# Generated by Django 3.2 on 2024-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaboleta',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
