# Generated by Django 3.2 on 2022-10-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionasiento',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('cortesia', 'Cortesía'), ('vendido', 'Vendido'), ('libre', 'Libre')], default='libre', max_length=30),
        ),
    ]
