# Generated by Django 3.2 on 2024-10-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0006_alter_programacionasiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionasiento',
            name='estado',
            field=models.CharField(choices=[('cortesia', 'Cortesía'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('libre', 'Libre')], default='libre', max_length=30),
        ),
    ]
