# Generated by Django 3.2 on 2022-10-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
        ("persona", "0001_initial"),
        ("venta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCaja", models.CharField(max_length=40)),
                ("montoEntrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("montoSalida", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresa.agencia",
                    ),
                ),
                ("cajeros", models.ManyToManyField(to="persona.Persona")),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
            },
        ),
        migrations.CreateModel(
            name="TipoMedioPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=100)),
                ("banco", models.CharField(blank=True, max_length=50, null=True)),
                ("numCuenta", models.CharField(blank=True, max_length=20, null=True)),
                ("numCci", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "TipoMedioPago",
                "verbose_name_plural": "TipoMedioPagos",
            },
        ),
        migrations.CreateModel(
            name="TipoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "TipoMovimiento",
                "verbose_name_plural": "TipoMovimientos",
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numMov", models.IntegerField(blank=True, null=True)),
                (
                    "movFecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Comprobante"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=7)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "evidencia",
                    models.ImageField(blank=True, null=True, upload_to="media/egreso"),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="caja.caja"
                    ),
                ),
                (
                    "cajero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cajero_movimientocaj",
                        to="persona.persona",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persona.persona",
                    ),
                ),
                (
                    "tipoMov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caja.tipomovimiento",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="venta.movimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "MovimientoCaja",
                "verbose_name_plural": "MovimientoCajas",
            },
        ),
        migrations.CreateModel(
            name="MedioPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "movimientoCaja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caja.movimientocaja",
                    ),
                ),
                (
                    "tipoMedioPago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caja.tipomediopago",
                    ),
                ),
            ],
            options={
                "verbose_name": "MedioPago",
                "verbose_name_plural": "MedioPagos",
            },
        ),
        migrations.CreateModel(
            name="CierreCajaMes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.SmallIntegerField()),
                ("mes", models.SmallIntegerField()),
                ("totalEntrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("totalSalida", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombrePeriodo", models.CharField(max_length=20)),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="caja.caja"
                    ),
                ),
                ("movimientoCaja", models.ManyToManyField(to="caja.MovimientoCaja")),
            ],
            options={
                "verbose_name": "CierreCajaMes",
                "verbose_name_plural": "CierreCajaMes",
            },
        ),
    ]
