# Generated by Django 3.2 on 2025-09-14 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_persona_ispersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCumpleanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('promo', models.TextField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumpleanos_registros', to='persona.personanatural')),
            ],
            options={
                'verbose_name': 'Registro de cumpleaños',
                'verbose_name_plural': 'Registros de cumpleaños',
                'unique_together': {('persona', 'fecha_envio')},
            },
        ),
    ]
