# Generated by Django 3.2 on 2024-10-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ispersonal',
            field=models.BooleanField(default=False),
        ),
    ]
