# Generated by Django 3.2 on 2025-09-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_ispersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='denominacion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Razón Social/Nombre y Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numDoc',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Numero Documento'),
        ),
    ]
