# Generated by Django 3.2 on 2022-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoAfectacionIgv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2)),
                ("descripcion", models.CharField(max_length=50)),
                ("codTributo", models.CharField(max_length=8)),
                ("codOse", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoAfectacionIgv",
                "verbose_name_plural": "TipoAfectacionIgv",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2)),
                ("descripcion", models.CharField(max_length=100)),
                ("codOse", models.CharField(blank=True, max_length=4, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoDocumento",
                "verbose_name_plural": "TipoDocumentos",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoIdentidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2)),
                ("descripcion", models.CharField(max_length=50)),
                ("codOse", models.CharField(blank=True, max_length=4, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoDocumentoIdentidad",
                "verbose_name_plural": "TipoDocumentoIdentidad",
            },
        ),
        migrations.CreateModel(
            name="TipoMoneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=5)),
                ("nomMoneda", models.CharField(max_length=50)),
                ("codOse", models.IntegerField(blank=True, null=True)),
                ("pais", models.CharField(max_length=50)),
                ("tipoCambio", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                "verbose_name": "TipoMoneda",
                "verbose_name_plural": "TipoMonedas",
            },
        ),
        migrations.CreateModel(
            name="TipoNotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2)),
                ("descripcion", models.CharField(max_length=50)),
                ("codOse", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoNotaCredito",
                "verbose_name_plural": "TipoNotaCreditos",
            },
        ),
        migrations.CreateModel(
            name="TipoNotaDebito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2)),
                ("descripcion", models.CharField(max_length=50)),
                ("codOse", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoNotaDebito",
                "verbose_name_plural": "TipoNotaDebito",
            },
        ),
        migrations.CreateModel(
            name="TipoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=4)),
                ("descripcion", models.CharField(max_length=50)),
                ("codOse", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TipoOperacion",
                "verbose_name_plural": "TipoOperacion",
            },
        ),
        migrations.CreateModel(
            name="Ubigeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8, verbose_name="Ubigeo")),
                ("distrito", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=255)),
                (
                    "numPoblacion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("superficie", models.CharField(blank=True, max_length=20, null=True)),
                ("cordY", models.CharField(blank=True, max_length=20, null=True)),
                ("cordX", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Ubigeo",
                "verbose_name_plural": "Ubigeos",
            },
        ),
    ]
