# Generated by Django 3.2 on 2022-10-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('pasadiso', 'Pasadiso'), ('cortesia', 'Cortesía'), ('libre', 'Libre')], default='libre', max_length=20, null=True),
        ),
    ]
