# Generated by Django 3.2 on 2024-10-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_asiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('pasadiso', 'Pasadiso'), ('libre', 'Libre'), ('cortesia', 'Cortesía')], default='libre', max_length=20, null=True),
        ),
    ]
