# Generated by Django 3.2 on 2025-09-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_asiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('cortesia', 'Cortesía'), ('pasadiso', 'Pasadiso'), ('libre', 'Libre')], default='libre', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duracion_aprox', models.DurationField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='empresa.agencia')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='empresa.agencia')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
